2025-09-17 19:17:31,527 | ERROR | restaurant_app | handle_exception:869 | Unhandled exception: 405 Method Not Allowed: The method is not allowed for the requested URL. - URL: http://127.0.0.1:5000/courier/order/9/delivered
2025-09-17 19:17:31,534 | ERROR | restaurant_app | handle_exception:871 | Full traceback:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

2025-09-18 23:08:20,581 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:08:20,631 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:08:53,888 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:08:53,912 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:09:39,881 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:09:39,999 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:09:53,839 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:09:53,857 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:10:34,684 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:10:34,738 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:10:39,865 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:10:39,877 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:10:44,884 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:10:44,923 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:10:50,714 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:10:50,734 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:11:39,867 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:11:39,876 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:11:50,887 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:11:50,897 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:12:39,862 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:12:39,873 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:12:50,880 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:12:50,893 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:13:39,858 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:13:39,877 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:13:50,890 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:13:50,902 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:14:36,280 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:14:36,294 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:14:39,867 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:14:39,878 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:16:36,619 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:16:36,650 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:16:39,850 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:16:39,866 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:17:36,907 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:17:36,907 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:17:48,428 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:17:48,441 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:18:36,884 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:18:36,892 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-18 23:18:39,868 | ERROR | restaurant_app | execute_query:1653 | Database operational error: no such table: news
2025-09-18 23:18:39,874 | ERROR | restaurant_app | api_news:13610 | API news error: no such table: news
2025-09-19 14:36:49,199 | ERROR | restaurant_app | menu:5524 | Menu endpoint error: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-09-19 14:36:49,379 | ERROR | restaurant_app | menu:5539 | Menu fallback error: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-09-19 14:38:51,292 | ERROR | restaurant_app | menu:5524 | Menu endpoint error: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-09-19 14:38:51,519 | ERROR | restaurant_app | menu:5539 | Menu fallback error: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-09-19 14:44:16,981 | ERROR | restaurant_app | menu:5524 | Menu endpoint error: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-09-19 14:44:17,006 | ERROR | restaurant_app | menu:5539 | Menu fallback error: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-09-19 14:52:50,603 | ERROR | restaurant_app | menu:5524 | Menu endpoint error: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-09-19 14:52:50,719 | ERROR | restaurant_app | menu:5539 | Menu fallback error: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-09-19 14:58:11,377 | ERROR | restaurant_app | menu:5524 | Menu endpoint error: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-09-19 14:58:11,392 | ERROR | restaurant_app | menu:5539 | Menu fallback error: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-09-19 15:01:30,207 | ERROR | restaurant_app | menu:5524 | Menu endpoint error: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-09-19 15:01:30,207 | ERROR | restaurant_app | menu:5539 | Menu fallback error: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-09-19 15:04:01,465 | ERROR | restaurant_app | menu:5524 | Menu endpoint error: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-09-19 15:04:01,476 | ERROR | restaurant_app | menu:5539 | Menu fallback error: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-09-19 17:59:43,580 | ERROR | restaurant_app | admin_news_management:14215 | News management page error: Could not build url for endpoint 'admin_card_management'. Did you mean 'admin_news_management' instead?
2025-09-19 18:00:12,544 | ERROR | restaurant_app | super_admin_dashboard:13022 | Super admin dashboard xatoligi: Could not build url for endpoint 'admin_card_management'. Did you mean 'admin_news_management' instead?
2025-09-19 18:00:13,106 | ERROR | restaurant_app | super_admin_dashboard:13022 | Super admin dashboard xatoligi: Could not build url for endpoint 'admin_card_management'. Did you mean 'admin_news_management' instead?
2025-09-19 18:00:16,557 | ERROR | restaurant_app | super_admin_dashboard:13022 | Super admin dashboard xatoligi: Could not build url for endpoint 'admin_card_management'. Did you mean 'admin_news_management' instead?
2025-09-19 18:01:01,758 | ERROR | restaurant_app | super_admin_dashboard:13022 | Super admin dashboard xatoligi: Could not build url for endpoint 'admin_card_management'. Did you mean 'admin_news_management' instead?
2025-09-19 18:01:20,244 | ERROR | restaurant_app | super_admin_dashboard:13022 | Super admin dashboard xatoligi: Could not build url for endpoint 'admin_card_management'. Did you mean 'admin_news_management' instead?
2025-09-19 18:02:07,071 | ERROR | restaurant_app | handle_exception:1035 | Unhandled exception: Could not build url for endpoint 'admin_card_management'. Did you mean 'admin_news_management' instead? - URL: http://127.0.0.1:5000/about
2025-09-19 18:02:07,103 | ERROR | restaurant_app | handle_exception:1035 | Unhandled exception: Could not build url for endpoint 'admin_card_management'. Did you mean 'admin_news_management' instead? - URL: http://127.0.0.1:5000/contact
2025-09-19 18:02:07,209 | ERROR | restaurant_app | handle_exception:1037 | Full traceback:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\OneDrive\Desktop\Pro-Obuv\app.py", line 7698, in about
    return render_template("about.html", current_page="about")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Moxir_Coder\OneDrive\Desktop\Pro-Obuv\templates\about.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Moxir_Coder\OneDrive\Desktop\Pro-Obuv\templates\base.html", line 687, in top-level template code
    <a class="nav-link" href="{{ url_for('admin_card_management') }}"
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'admin_card_management'. Did you mean 'admin_news_management' instead?

2025-09-19 18:02:07,209 | ERROR | restaurant_app | handle_exception:1037 | Full traceback:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\OneDrive\Desktop\Pro-Obuv\app.py", line 7692, in contact
    return render_template("contact.html", current_page="contact")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Moxir_Coder\OneDrive\Desktop\Pro-Obuv\templates\contact.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Moxir_Coder\OneDrive\Desktop\Pro-Obuv\templates\base.html", line 687, in top-level template code
    <a class="nav-link" href="{{ url_for('admin_card_management') }}"
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'admin_card_management'. Did you mean 'admin_news_management' instead?

2025-09-19 18:02:08,453 | ERROR | restaurant_app | super_admin_dashboard:13022 | Super admin dashboard xatoligi: Could not build url for endpoint 'admin_card_management'. Did you mean 'admin_news_management' instead?
2025-09-19 18:03:56,510 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: card_payment_settings
2025-09-19 18:03:56,511 | ERROR | restaurant_app | api_get_card_data:14312 | Get card data error: no such table: card_payment_settings
2025-09-19 18:04:02,131 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: photos_360
2025-09-19 18:04:02,133 | ERROR | restaurant_app | api_get_360_photos:14435 | Get 360 photos error: no such table: photos_360
2025-09-19 18:04:08,404 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: card_payment_settings
2025-09-19 18:04:08,407 | ERROR | restaurant_app | api_get_card_data:14312 | Get card data error: no such table: card_payment_settings
2025-09-19 18:04:37,924 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: photos_360
2025-09-19 18:04:37,926 | ERROR | restaurant_app | api_get_360_photos:14435 | Get 360 photos error: no such table: photos_360
2025-09-19 18:04:39,055 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: card_payment_settings
2025-09-19 18:04:39,059 | ERROR | restaurant_app | api_get_card_data:14312 | Get card data error: no such table: card_payment_settings
2025-09-19 18:04:41,298 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: photos_360
2025-09-19 18:04:41,299 | ERROR | restaurant_app | api_get_360_photos:14435 | Get 360 photos error: no such table: photos_360
2025-09-19 18:04:57,180 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: card_payment_settings
2025-09-19 18:04:57,180 | ERROR | restaurant_app | api_get_card_data:14350 | Get card data error: no such table: card_payment_settings
2025-09-19 18:06:05,535 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: photos_360
2025-09-19 18:06:05,536 | ERROR | restaurant_app | api_get_360_photos:14473 | Get 360 photos error: no such table: photos_360
2025-09-19 18:07:48,801 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: card_payment_settings
2025-09-19 18:07:48,804 | ERROR | restaurant_app | api_get_card_data:14350 | Get card data error: no such table: card_payment_settings
2025-09-19 18:08:01,983 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: photos_360
2025-09-19 18:08:01,984 | ERROR | restaurant_app | api_get_360_photos:14473 | Get 360 photos error: no such table: photos_360
2025-09-19 18:17:05,522 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: photos_360
2025-09-19 18:17:05,523 | ERROR | restaurant_app | api_get_active_360_photos:14488 | Get active 360 photos error: no such table: photos_360
2025-09-19 18:17:58,505 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: card_payment_settings
2025-09-19 18:17:58,507 | ERROR | restaurant_app | api_get_card_data:14350 | Get card data error: no such table: card_payment_settings
2025-09-19 18:19:52,567 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: card_payment_settings
2025-09-19 18:19:52,576 | ERROR | restaurant_app | api_get_card_data:14350 | Get card data error: no such table: card_payment_settings
2025-09-19 18:19:55,229 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: photos_360
2025-09-19 18:19:55,232 | ERROR | restaurant_app | api_get_360_photos:14473 | Get 360 photos error: no such table: photos_360
2025-09-19 18:19:57,062 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: card_payment_settings
2025-09-19 18:19:57,064 | ERROR | restaurant_app | api_get_card_data:14350 | Get card data error: no such table: card_payment_settings
2025-09-19 18:21:01,241 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: card_payment_settings
2025-09-19 18:21:01,250 | ERROR | restaurant_app | api_get_card_data:14350 | Get card data error: no such table: card_payment_settings
2025-09-19 18:25:17,942 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: card_payment_settings
2025-09-19 18:25:17,947 | ERROR | restaurant_app | api_get_card_data:14350 | Get card data error: no such table: card_payment_settings
2025-09-19 18:36:12,274 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: card_payment_settings
2025-09-19 18:36:12,288 | ERROR | restaurant_app | api_get_card_data:14350 | Get card data error: no such table: card_payment_settings
2025-09-19 18:49:37,393 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: payment_cards
2025-09-19 18:49:37,394 | ERROR | restaurant_app | api_get_payment_methods:8761 | Get payment methods error: no such table: payment_cards
2025-09-19 18:53:40,176 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: payment_cards
2025-09-19 18:53:40,178 | ERROR | restaurant_app | api_get_payment_methods:8761 | Get payment methods error: no such table: payment_cards
2025-09-19 18:54:03,333 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: payment_cards
2025-09-19 18:54:03,336 | ERROR | restaurant_app | api_get_payment_methods:8761 | Get payment methods error: no such table: payment_cards
2025-09-19 18:54:18,124 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: photos_360
2025-09-19 18:54:18,125 | ERROR | restaurant_app | api_get_active_360_photos:14538 | Get active 360 photos error: no such table: photos_360
2025-09-19 18:54:33,187 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: card_payment_settings
2025-09-19 18:54:33,187 | ERROR | restaurant_app | api_get_card_data:14400 | Get card data error: no such table: card_payment_settings
2025-09-19 18:54:47,968 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: card_payment_settings
2025-09-19 18:54:47,970 | ERROR | restaurant_app | api_get_card_data:14400 | Get card data error: no such table: card_payment_settings
2025-09-19 18:54:49,058 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: photos_360
2025-09-19 18:54:49,061 | ERROR | restaurant_app | api_get_360_photos:14523 | Get 360 photos error: no such table: photos_360
2025-09-19 18:54:58,000 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: photos_360
2025-09-19 18:54:58,001 | ERROR | restaurant_app | api_upload_360_photos:14609 | Upload 360 photos error: no such table: photos_360
2025-09-19 18:55:23,498 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: photos_360
2025-09-19 18:55:23,499 | ERROR | restaurant_app | api_upload_360_photos:14609 | Upload 360 photos error: no such table: photos_360
2025-09-19 18:55:31,690 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: photos_360
2025-09-19 18:55:31,691 | ERROR | restaurant_app | api_get_active_360_photos:14538 | Get active 360 photos error: no such table: photos_360
2025-09-19 18:57:09,718 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: card_payment_settings
2025-09-19 18:57:09,720 | ERROR | restaurant_app | api_get_card_data:14400 | Get card data error: no such table: card_payment_settings
2025-09-19 18:57:18,541 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: payment_cards
2025-09-19 18:57:18,542 | ERROR | restaurant_app | api_get_payment_methods:8761 | Get payment methods error: no such table: payment_cards
2025-09-19 18:57:22,187 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: payment_cards
2025-09-19 18:57:22,188 | ERROR | restaurant_app | api_get_payment_methods:8761 | Get payment methods error: no such table: payment_cards
2025-09-19 18:58:01,986 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: photos_360
2025-09-19 18:58:01,990 | ERROR | restaurant_app | api_get_360_photos:14523 | Get 360 photos error: no such table: photos_360
2025-09-19 18:58:10,460 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: photos_360
2025-09-19 18:58:10,461 | ERROR | restaurant_app | api_get_360_photos:14523 | Get 360 photos error: no such table: photos_360
2025-09-19 19:29:23,610 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: payment_cards
2025-09-19 19:29:23,611 | ERROR | restaurant_app | api_get_payment_methods:8793 | Get payment methods error: no such table: payment_cards
2025-09-19 19:29:34,736 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: card_payment_settings
2025-09-19 19:29:34,740 | ERROR | restaurant_app | api_get_card_data:14432 | Get card data error: no such table: card_payment_settings
2025-09-19 19:29:42,463 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: card_payment_settings
2025-09-19 19:29:42,463 | ERROR | restaurant_app | api_save_card_data:14474 | Save card data error: no such table: card_payment_settings
2025-09-19 19:29:45,969 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: card_payment_settings
2025-09-19 19:29:45,970 | ERROR | restaurant_app | api_save_card_data:14474 | Save card data error: no such table: card_payment_settings
2025-09-19 19:29:53,168 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: photos_360
2025-09-19 19:29:53,182 | ERROR | restaurant_app | api_get_360_photos:14553 | Get 360 photos error: no such table: photos_360
2025-09-19 19:29:59,297 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: photos_360
2025-09-19 19:29:59,297 | ERROR | restaurant_app | api_upload_360_photos:14623 | Upload 360 photos error: no such table: photos_360
2025-09-19 19:30:18,073 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such table: card_payment_settings
2025-09-19 19:30:18,079 | ERROR | restaurant_app | api_get_card_data:14432 | Get card data error: no such table: card_payment_settings
2025-09-19 19:40:06,064 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such column: card_name
2025-09-19 19:40:06,066 | ERROR | restaurant_app | api_get_payment_methods:8809 | Get payment methods error: no such column: card_name
2025-09-19 19:41:03,089 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such column: card_name
2025-09-19 19:41:03,090 | ERROR | restaurant_app | api_get_payment_methods:8809 | Get payment methods error: no such column: card_name
2025-09-19 19:45:06,360 | ERROR | restaurant_app | execute_query:1819 | Database operational error: no such column: bank_name
2025-09-19 19:45:06,362 | ERROR | restaurant_app | api_get_payment_methods:8809 | Get payment methods error: no such column: bank_name
2025-09-19 20:50:51,323 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 334, in execute
    write(data)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 309, in write
    self.wfile.write(data)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 834, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:55:32,256 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:55:32,471 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:55:33,610 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:55:36,083 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:55:36,117 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:13,762 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:13,766 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:13,771 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:13,773 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:13,776 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:22,523 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:22,829 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:22,836 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:22,876 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:22,886 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:22,918 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:22,929 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:22,937 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:22,948 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:22,964 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:26,632 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:26,648 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:26,910 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:26,945 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:26,960 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:26,960 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:26,979 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:26,994 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:27,023 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:27,245 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:27,418 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:27,472 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:27,478 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:27,662 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:27,662 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:27,812 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:27,858 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:27,861 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:27,953 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:27,991 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 20:56:28,018 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,310 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,311 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,311 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,312 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,312 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,315 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,323 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,330 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,337 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,345 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,352 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,360 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,366 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,372 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,379 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,385 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,391 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,398 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,407 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,414 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,420 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,428 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,435 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,449 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,454 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,463 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,470 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,478 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,486 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,495 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,503 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,512 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,520 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,529 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,536 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,543 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,550 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,558 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,564 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,571 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,578 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,584 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,591 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,597 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,603 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,610 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,616 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,621 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,629 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,639 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,646 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,652 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,660 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,666 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,672 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,678 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,684 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,697 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,704 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,713 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,721 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,728 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,734 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,741 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,747 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,754 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,762 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,768 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,775 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,781 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,789 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,796 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,804 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,812 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 22:48:22,823 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-19 23:22:00,713 | ERROR | restaurant_app | menu:5875 | Menu endpoint error: Encountered unknown tag 'endblock'.
2025-09-19 23:22:00,740 | ERROR | restaurant_app | menu:5890 | Menu fallback error: Encountered unknown tag 'endblock'.
2025-09-19 23:22:10,272 | ERROR | restaurant_app | menu:5875 | Menu endpoint error: Encountered unknown tag 'endblock'.
2025-09-19 23:22:10,284 | ERROR | restaurant_app | menu:5890 | Menu fallback error: Encountered unknown tag 'endblock'.
2025-09-19 23:25:28,639 | ERROR | restaurant_app | menu:5875 | Menu endpoint error: Encountered unknown tag 'endblock'.
2025-09-19 23:25:28,669 | ERROR | restaurant_app | menu:5890 | Menu fallback error: Encountered unknown tag 'endblock'.
2025-09-19 23:30:29,402 | ERROR | restaurant_app | menu:5875 | Menu endpoint error: Encountered unknown tag 'endblock'.
2025-09-19 23:30:29,418 | ERROR | restaurant_app | menu:5890 | Menu fallback error: Encountered unknown tag 'endblock'.
2025-09-19 23:35:49,409 | ERROR | restaurant_app | menu:5875 | Menu endpoint error: Encountered unknown tag 'endblock'.
2025-09-19 23:35:49,434 | ERROR | restaurant_app | menu:5890 | Menu fallback error: Encountered unknown tag 'endblock'.
2025-09-20 07:53:44,180 | ERROR | restaurant_app | menu:5926 | Menu endpoint error: Encountered unknown tag 'endblock'.
2025-09-20 07:53:44,198 | ERROR | restaurant_app | menu:5941 | Menu fallback error: Encountered unknown tag 'endblock'.
2025-09-20 07:55:41,248 | ERROR | restaurant_app | menu:5926 | Menu endpoint error: Encountered unknown tag 'endblock'.
2025-09-20 07:55:41,264 | ERROR | restaurant_app | menu:5941 | Menu fallback error: Encountered unknown tag 'endblock'.
2025-09-20 07:58:31,583 | ERROR | restaurant_app | menu:5926 | Menu endpoint error: Encountered unknown tag 'endblock'.
2025-09-20 07:58:31,599 | ERROR | restaurant_app | menu:5941 | Menu fallback error: Encountered unknown tag 'endblock'.
2025-09-20 11:06:36,984 | ERROR | restaurant_app | super_admin_dashboard:13552 | Super admin dashboard xatoligi: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-09-20 11:06:38,929 | ERROR | restaurant_app | super_admin_dashboard:13552 | Super admin dashboard xatoligi: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-09-20 11:11:59,722 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,725 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,740 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,751 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,766 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,777 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,786 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,794 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,801 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,809 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,817 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,824 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,833 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,845 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,851 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,858 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,867 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,877 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,885 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,893 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,900 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,907 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,914 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,921 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,928 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,935 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,941 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,947 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,953 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,961 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,968 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,974 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,982 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,988 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:11:59,994 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,001 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,010 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,038 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,048 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,143 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,153 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,163 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,173 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,183 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,193 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,204 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,214 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,224 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,235 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,242 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,253 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,263 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,273 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,282 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,291 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,300 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,308 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,318 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,326 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,338 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,348 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,357 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,365 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,373 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,383 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,392 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,402 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,411 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,421 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,429 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,439 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,445 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,453 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,460 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,469 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,478 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,486 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,494 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,503 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,510 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,519 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,526 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,536 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,544 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,553 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,560 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,571 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,578 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,586 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,593 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,603 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:00,611 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,194 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,223 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,234 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,247 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,260 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,271 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,279 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,294 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,306 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,316 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,326 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,336 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,348 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,358 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,368 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,379 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,394 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,408 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,430 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,441 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,476 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,488 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,521 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,541 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,572 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,591 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,639 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,658 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,679 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,687 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,698 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,708 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:01,725 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:43,992 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,484 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,499 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,515 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,529 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,544 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,561 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,575 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,591 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,638 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,653 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,668 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,714 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,819 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,855 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,875 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,896 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,910 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,928 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,943 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-20 11:12:44,955 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:22:08,228 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:22:09,051 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:22:16,873 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:22:16,905 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:22:16,914 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:22:16,918 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:22:16,920 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:22:16,923 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:25:33,805 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:25:33,805 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:25:33,813 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:25:33,821 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:25:33,829 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:25:33,829 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:27:17,800 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:27:17,800 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:27:17,808 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:27:17,816 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
2025-09-21 17:27:18,831 | ERROR | werkzeug | _log:97 | Error on request:
Traceback (most recent call last):
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Moxir_Coder\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 355, in execute
    data = self.rfile.read(10_000_000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
